version: '3.4'

services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: webapp
    volumes:
       - ./webapp:/usr/src/app/webapp
       - /usr/src/app/webapp/node_modules
  
  get_control_db:
    container_name: get_control_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=get_control_db
    volumes:
      - pg-data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: api
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
    env_file:
      - api/.env

volumes:
  pg-data: