version: '3.4'

services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: webapp
    volumes:
       - ./webapp:/usr/src/app/webapp
       - /usr/src/app/webapp/node_modules
